In [1]:
import numpy as np

In [2]:
n, m = 5, 3

x = np.arange(n * m).reshape((n, m))

In [3]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
for index, item in enumerate(x):
    print(index)
    print(item)

0
[0 1 2]
1
[3 4 5]
2
[6 7 8]
3
[ 9 10 11]
4
[12 13 14]
