In [1]:
import numpy as np

In [11]:
x = np.zeros((3, 4), dtype=float)

In [12]:
b = np.array([1, 2, 3, 4])

In [13]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
b

array([1, 2, 3, 4])

In [15]:
x + b[None, :]

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [17]:
b[None, :] + b[:, None]

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])