In [1]:
import numpy as np

In [2]:
n, m = 5, 3

x = np.arange(n * m).reshape((n, m))

In [3]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
np.mean(x, axis=0)

array([6., 7., 8.])

In [5]:
np.mean(x, axis=1)

array([ 1.,  4.,  7., 10., 13.])