In [1]:
import numpy as np

In [2]:
x = np.arange(6).reshape((3, 2))

In [3]:
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
np.sum(x, axis=1)

array([1, 5, 9])

In [5]:
x / np.sum(x, axis=1)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [6]:
np.sum(x, axis=1, keepdims=True)

array([[1],
       [5],
       [9]])

In [7]:
x / np.sum(x, axis=1, keepdims=True)

array([[0.        , 1.        ],
       [0.4       , 0.6       ],
       [0.44444444, 0.55555556]])

In [8]:
np.divide(x, np.sum(x, axis=1))

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [9]:
x / np.sum(x, axis=1).reshape(-1,1)

array([[0.        , 1.        ],
       [0.4       , 0.6       ],
       [0.44444444, 0.55555556]])